// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=../usecase/test/mocks_repo_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	entity "go-eprescription-clean/internal/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSignaRepo is a mock of SignaRepo interface.
type MockSignaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSignaRepoMockRecorder
	isgomock struct{}
}

// MockSignaRepoMockRecorder is the mock recorder for MockSignaRepo.
type MockSignaRepoMockRecorder struct {
	mock *MockSignaRepo
}

// NewMockSignaRepo creates a new mock instance.
func NewMockSignaRepo(ctrl *gomock.Controller) *MockSignaRepo {
	mock := &MockSignaRepo{ctrl: ctrl}
	mock.recorder = &MockSignaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignaRepo) EXPECT() *MockSignaRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSignaRepo) Create(arg0 context.Context, arg1 entity.Signa) (*entity.Signa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*entity.Signa)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSignaRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSignaRepo)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockSignaRepo) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSignaRepoMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSignaRepo)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockSignaRepo) GetAll(arg0 context.Context) ([]entity.Signa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]entity.Signa)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSignaRepoMockRecorder) GetAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSignaRepo)(nil).GetAll), arg0)
}

// GetByID mocks base method.
func (m *MockSignaRepo) GetByID(arg0 context.Context, arg1 string) (*entity.Signa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Signa)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSignaRepoMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSignaRepo)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockSignaRepo) Update(arg0 context.Context, arg1 string, arg2 entity.Signa) (*entity.Signa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.Signa)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSignaRepoMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSignaRepo)(nil).Update), arg0, arg1, arg2)
}

// MockPatientRepo is a mock of PatientRepo interface.
type MockPatientRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPatientRepoMockRecorder
	isgomock struct{}
}

// MockPatientRepoMockRecorder is the mock recorder for MockPatientRepo.
type MockPatientRepoMockRecorder struct {
	mock *MockPatientRepo
}

// NewMockPatientRepo creates a new mock instance.
func NewMockPatientRepo(ctrl *gomock.Controller) *MockPatientRepo {
	mock := &MockPatientRepo{ctrl: ctrl}
	mock.recorder = &MockPatientRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientRepo) EXPECT() *MockPatientRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPatientRepo) Create(arg0 context.Context, arg1 entity.Patient) (*entity.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*entity.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPatientRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPatientRepo)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockPatientRepo) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPatientRepoMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPatientRepo)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockPatientRepo) GetAll(arg0 context.Context) ([]entity.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]entity.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPatientRepoMockRecorder) GetAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPatientRepo)(nil).GetAll), arg0)
}

// GetByID mocks base method.
func (m *MockPatientRepo) GetByID(arg0 context.Context, arg1 string) (*entity.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPatientRepoMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPatientRepo)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockPatientRepo) Update(arg0 context.Context, arg1 string, arg2 entity.Patient) (*entity.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPatientRepoMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPatientRepo)(nil).Update), arg0, arg1, arg2)
}

// MockMedicineRepo is a mock of MedicineRepo interface.
type MockMedicineRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMedicineRepoMockRecorder
	isgomock struct{}
}

// MockMedicineRepoMockRecorder is the mock recorder for MockMedicineRepo.
type MockMedicineRepoMockRecorder struct {
	mock *MockMedicineRepo
}

// NewMockMedicineRepo creates a new mock instance.
func NewMockMedicineRepo(ctrl *gomock.Controller) *MockMedicineRepo {
	mock := &MockMedicineRepo{ctrl: ctrl}
	mock.recorder = &MockMedicineRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMedicineRepo) EXPECT() *MockMedicineRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMedicineRepo) Create(arg0 context.Context, arg1 entity.Medicine) (*entity.Medicine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*entity.Medicine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMedicineRepoMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMedicineRepo)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockMedicineRepo) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMedicineRepoMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMedicineRepo)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockMedicineRepo) GetAll(arg0 context.Context) ([]entity.Medicine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0)
	ret0, _ := ret[0].([]entity.Medicine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMedicineRepoMockRecorder) GetAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMedicineRepo)(nil).GetAll), arg0)
}

// GetByID mocks base method.
func (m *MockMedicineRepo) GetByID(arg0 context.Context, arg1 string) (*entity.Medicine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Medicine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMedicineRepoMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMedicineRepo)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockMedicineRepo) Update(arg0 context.Context, arg1 string, arg2 entity.Medicine) (*entity.Medicine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.Medicine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMedicineRepoMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMedicineRepo)(nil).Update), arg0, arg1, arg2)
}
